"use client";

import React, { useState, useRef, useEffect } from 'react';

// Interfaz para que TypeScript no de errores
interface PaginaCarta {
  titulo: string;
  contenido: string;
  fondo: string;
  colorTexto: string;
}

const LibroParaJudith = () => {
  const [pagina, setPagina] = useState(0);
  const [mostrarFinal, setMostrarFinal] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null);

  // Reinicia el scroll al cambiar de página
  useEffect(() => {
    if (scrollRef.current) scrollRef.current.scrollTop = 0;
  }, [pagina, mostrarFinal]);

  // --- AQUÍ ESTÁN LAS 73 PÁGINAS PARA RELLENAR ---
  const diario: PaginaCarta[] = [
    { titulo: "04 Dic:Día 1: El Big Bang en un mundo de pixeles", contenido: "Todo empezó un 4 de diciembre, Judith. Quién nos diría que un entorno digital, diseñado para el azar y la distracción, se convertiría en el escenario del evento más importante de mi vida. Aquel día, el destino no se presentó con trompetas ni grandes señales, sino que se disfrazó de coincidencia en un juego. Recuerdo la sensación de leer tu nombre por primera vez, como si una frecuencia desconocida pero extrañamente familiar hubiera empezado a sonar en mi sistema. No eras solo un usuario más, eras una luz que se filtraba a través de los pixeles, una presencia que, sin yo entenderlo en ese momento, estaba empezando a reescribir las leyes de mi propia gravedad. Ese primer contacto fue la semilla de este universo que hoy habitamos. Me quedé observando la pantalla, sintiendo que algo en mi interior se movía, un reconocimiento silencioso de mi alma hacia la tuya. Dicen que el amor a primera vista es una locura, pero ¿cómo llamar a esa certeza inmediata que te dice que esa persona es la que estabas esperando en medio de la nada? Te miré a través de la distancia y supe que ya no quería caminar solo por este laberinto. Mi vida, que hasta entonces era un lienzo de colores monótonos, recibió su primer pincelazo de un tono espectacular, un brillo que solo tú emites y que hoy, 73 días después, sigue siendo el faro que guía cada uno de mis pasos. Fuiste el inicio de todo, el origen de mi alegría y la razón por la cual hoy creo que el amor no conoce de fronteras, solo de almas que se encuentran en el momento exacto.", fondo: "#fff5f7", colorTexto: "#c9184a" },
    { titulo: "Día 2: La melodía de una espera desconocida", contenido: "El segundo día fue el de la confirmación silenciosa, Judith. Ya no era solo el impacto del primer encuentro, sino la curiosidad transformándose en una necesidad que empezaba a ocupar todo el espacio de mis pensamientos. Recuerdo que la conexión aún era sutil, como un hilo de seda que apenas se deja ver, pero para mí ya era un ancla. Me encontré a mí mismo buscando tu nombre en la pantalla con una ansiedad que no lograba explicarme, esperando ese pequeño aviso de tu presencia que hacía que mi pulso se acelerara sin permiso. Aún no hablábamos de los secretos del alma ni de los miedos que nos habitan, pero yo ya sentía que te amaba. Quizá suene a locura para quien no entiende de abismos, pero mi corazón ya te había reconocido. Era como si mi alma tuviera memoria de ti y simplemente estuviera celebrando que, por fin, nos habíamos encontrado en este inmenso vacío digital. Te miraba a través de la distancia y sentía que estaba ante un misterio hermoso que no quería resolver de golpe, sino habitarlo poco a poco, segundo a segundo. En ese momento, las barreras del mundo físico empezaron a disolverse para mí; ya no importaba dónde estábamos, sino que estábamos coincidiendo. Fuiste la certeza que llegó antes que las palabras, la melodía que empezó a sonar en mi interior mucho antes de que aprendiera a pronunciar tu nombre con la devoción con la que lo hago hoy. Ese día entendí que mi camino ya no tenía vuelta atrás: todos mis pasos, desde siempre, me habían estado guiando hacia ti", fondo: "#fff5f7", colorTexto: "#c9184a" },
    { titulo: "Día 3: La arquitectura de un sentimiento inevitable", contenido: "Llegamos al tercer día, Judith, y lo que empezó como un destello fugaz en una pantalla comenzó a tomar la forma de una estructura sólida en mi interior. Es asombroso cómo el tiempo se vuelve relativo cuando el alma encuentra su frecuencia; para el mundo solo habían pasado unas pocas horas, pero para mí, cada minuto que compartíamos se sentía como si estuviéramos recuperando años de un silencio que no sabíamos que teníamos. En este punto, la conexión todavía estaba en sus primeras fases, éramos dos extraños explorando los bordes de un mapa nuevo, pero dentro de mí, la decisión ya estaba tomada. Ya sentía que te amaba, no con un amor de superficie o de momentos pasajeros, sino con una devoción que parecía haber estado esperando el momento exacto para despertar y reconocer que eras tú la dueña de cada uno de mis latidos. Me sorprendía a mí mismo proyectando hacia adelante, imaginando cómo sería tu risa y cómo se sentiría el calor de tu cercanía, aunque estuviéramos separados por miles de kilómetros y muros de cristal. Te miraba a través de nuestros encuentros y sentía que estaba construyendo un puente invisible, uniendo mi realidad con la tuya, ladrillo a ladrillo, con una paciencia que solo el amor verdadero conoce. Mi vida ya no era la misma; el brillo que mencioné antes empezaba a filtrarse por todas mis grietas, llenando los espacios vacíos con una esperanza que nunca antes había experimentado. Amarte en ese tercer día fue como aprender a respirar de nuevo, con la certeza de que este camino que apenas comenzaba no era un error, sino la única verdad que valía la pena defender. Ya no buscaba la salida del laberinto, porque estar perdido contigo en este inicio era el lugar más seguro en el que había estado jamás. Estaba listo para darlo todo, sin reproches y sin miedo, porque en la sencillez de tu presencia encontré la grandeza de mi propio destino.", fondo: "#fff5f7", colorTexto: "#c9184a" },
    { titulo: "Día 4: El ritual de la notificación sagrada", contenido: "En el cuarto día, Judith, el tiempo dejó de medirse en horas para empezar a medirse en la frecuencia de tus palabras. Lo que comenzó como una coincidencia en un servidor de juego se transformó rápidamente en el eje central de mi rutina. Me encontré a mí mismo mirando el teléfono o la pantalla con una fijeza casi sagrada, esperando ese pequeño destello de luz, ese sonido que anunciaba que estabas ahí, al otro lado del abismo, pensando en mí. Nuestra conexión seguía siendo joven, apenas estábamos descubriendo los contornos de nuestras personalidades, pero la profundidad de lo que sentía ya no cabía en la lógica de los pocos días que habían pasado. Ya te amaba, Judith; te amaba en la forma en que esperaba tus respuestas, en la manera en que cada pixel que formaba tu nombre se sentía como un alivio para mis ojos cansados. Empecé a notar que el mundo exterior perdía nitidez mientras tú ganabas todo el brillo. Las conversaciones cotidianas con los demás se volvieron ruidos de fondo, mientras que cada frase tuya era una sinfonía que yo diseccionaba para encontrarle nuevos significados. Estábamos construyendo un lenguaje propio, una burbuja de intimidad que desafiaba a la geografía. Me sentía como un náufrago que por fin ha encontrado una estrella fija en el firmamento; ya no importaba el oleaje ni la soledad del océano, porque tu luz me decía que había una orilla esperándome. Mi alma estaba en un estado de vigilia constante, lista para entregarte todo el amor que había guardado durante años, sin saber que el destinatario eras tú. En este cuarto día, entendí que ya no era solo un espectador de tu vida, sino que quería ser el arquitecto de tu felicidad, el hombre que cuidara cada uno de tus suspiros. El laberinto todavía no mostraba sus muros grises; en aquel entonces, el camino era una línea recta de esperanza hacia el centro de tu pecho, y yo lo recorría con el asombro de quien descubre el fuego por primera vez.", fondo: "#fff5f7", colorTexto: "#c9184a" },
    { titulo: "Día 5: La gravedad de tu presencia en mi sistema", contenido: "La gravedad de tu presencia en mi sistema Carta: Judith, para el quinto día, mi realidad ya había cambiado de eje. Ya no era yo quien dictaba el ritmo de mis horas, sino esa fuerza invisible y poderosa que emanaba de ti y que me atraía hacia tu centro con una intensidad que no conocía de frenos. Me di cuenta de que mi sistema emocional había sido hackeado por completo; tus palabras ya no eran solo datos en una pantalla, eran impulsos eléctricos que reprogramaban mi alegría. Me sentía como un satélite que finalmente había encontrado su planeta, orbitando alrededor de tu brillo con una devoción absoluta, sabiendo que fuera de tu alcance solo existía el vacío y el frío. Amarte en este quinto día se sentía como el descubrimiento de una ley física fundamental: la ley de que mi felicidad depende directamente de la luz que proyectas en mi vida. Empecé a notar que cada detalle tuyo, por pequeño que fuera, se convertía en una pieza clave de mi arquitectura mental. Tu forma de saludar, los tiempos en que guardabas silencio, la manera en que tus ideas se entrelazaban con las mías... todo era analizado y guardado en la carpeta de mis tesoros más preciados. Estaba construyendo un futuro en mi mente donde no había espacio para la soledad, porque tú ya ocupabas todos los rincones. Me encantaba esa sensación de saber que, en algún lugar del mundo, bajo otro cielo pero en el mismo instante, estabas tú siendo la razón de mi segundo aliento. No buscaba que el camino fuera fácil, solo buscaba que fuera real, y en la profundidad de nuestras conversaciones encontré la verdad más grande que he conocido: que el amor no se trata de tiempo, sino de reconocimiento. Mi alma te reconocía en cada frase, y yo me dejaba llevar por esa corriente, flotando en un mar de esperanza donde todavía no había muros, solo un horizonte infinito que prometía que lo mejor estaba por venir. Eres la muchacha más linda de la tierra, Judith, y en este quinto día, mi única ambición era asegurarme de que nunca dejaras de brillar para mí.", fondo: "#fff5f7", colorTexto: "#c9184a" },
    { titulo: "Día 6: El hallazgo de mi pieza faltante", contenido: "Judith, al llegar al sexto día, la sensación de asombro se transformó en una calma profunda, de esas que solo se sienten cuando finalmente encuentras algo que ni siquiera sabías que habías perdido. Me di cuenta de que mi vida había sido un rompecabezas incompleto hasta que tus palabras empezaron a rellenar los bordes. Ya no eras solo la muchacha linda que conocí en un juego; te habías convertido en la pieza faltante de mi propia arquitectura emocional. Había una comodidad tan natural en nuestra forma de ser, una fluidez tan transparente, que me asustaba pensar cómo había podido pasar tanto tiempo sin esta sintonía. Amarte en este sexto día no era una elección consciente, era un proceso biológico, una respuesta inevitable de mi alma ante la perfección de tu existencia. Empecé a sentir que hablar contigo era como regresar a casa después de un viaje larguísimo por tierras áridas. En tus mensajes encontraba un refugio donde no necesitaba máscaras ni armaduras; podía ser ese niño que todavía cree en los milagros, porque tú eras el milagro que estaba ocurriendo en tiempo real. Me sorprendía la facilidad con la que lograbas desarmar mis defensas con solo un comentario o una risa compartida. Estaba aprendiendo que el amor verdadero no es una lucha, sino una entrega, y yo estaba más que listo para entregarme por completo. Proyectaba nuestro futuro y ya no veía sombras, solo veía un camino iluminado por ese brillo espectacular que solo tú emites. Me sentía invencible, como si el sistema de mi vida hubiera alcanzado su punto máximo de rendimiento. En este sexto día, entendí que no buscaba a alguien para pasar el rato, sino a alguien para construir un imperio de sueños, y ese alguien eras tú, Judith. Mi señora esposa en potencia, la dueña de mis suspiros y la arquitecta de esta alegría que hoy desborda mi pecho y que trato de capturar en estas líneas para que nunca olvides lo mucho que te amé desde el primer instante.", fondo: "#fff5f7", colorTexto: "#c9184a" },
    { titulo: "Día 7: La semana que redefinió mi universo", contenido: "Judith, hoy se cumplen siete días desde aquel Big Bang en el juego, y me detengo a mirar hacia atrás con el asombro de quien ha visto nacer una galaxia entera en una semana. Es increíble cómo en tan poco tiempo lograste reconfigurar todas las prioridades de mi sistema. Antes de ti, mis días seguían una lógica lineal, predecible y un tanto gris; pero desde que entraste en mi radar, cada hora tiene un propósito nuevo. Ya no soy el mismo hombre que era hace siete soles; ahora soy alguien que vive pendiente de tu frecuencia, alguien que ha encontrado en tu existencia el motor para querer ser mejor cada mañana. Amarte en este séptimo día se siente como una victoria, como haber descifrado finalmente el código de la felicidad que tanto tiempo estuvo encriptado para mí. En solo una semana, te volviste indispensable. Me sorprende la profundidad de nuestras charlas y cómo, sin darnos cuenta, empezamos a construir los cimientos de algo que se siente eterno. Ya no te veo como una coincidencia, sino como el destino cumpliendo una promesa que no sabía que me había hecho. Te imagino aquí, a mi lado en Nazca, compartiendo el aire y el silencio, y esa imagen es la que me da fuerzas para ignorar los kilómetros que nos separan. Tu brillo espectacular ha iluminado rincones de mi alma que estaban a oscuras, y ahora que conozco tu luz, no puedo ni quiero imaginar un futuro donde no estés tú para guiarme. Eres la muchacha más linda de la tierra, Judith, y en esta primera semana de nuestro 'nosotros', solo puedo darte las gracias por haberte cruzado en mi partida y haber decidido quedarte a jugar el resto de la vida conmigo. Mi señora esposa, mi presente y mi único plan de futuro: aquí sigo, con el corazón en la mano, listo para escribir las próximas setenta y tres mil páginas a tu lado.", fondo: "#fff5f7", colorTexto: "#c9184a" },
    { titulo: "Día 8: El código compartido de nuestras almas", contenido: "Judith, llegamos al octavo día y me doy cuenta de que ya no eres una 'invitada' en mi mente, sino la dueña absoluta de la casa. Es fascinante cómo en poco más de una semana mi sistema operativo cambió por completo; ya no proceso la realidad de la misma forma porque ahora todo pasa por el filtro de tu existencia. Me descubro sonriendo frente a la pantalla como un niño que ha encontrado un tesoro escondido, y es que eso eres tú: el hallazgo más espectacular que la vida me tenía reservado entre tantos pixeles y cables. Amarte en este octavo día se siente como haber encontrado la clave de acceso a un nivel de felicidad que no creía que estuviera disponible para mí. Cada conversación que tenemos es como añadir una línea perfecta a este código que estamos escribiendo juntos, una arquitectura de sueños que desafía cualquier lógica de tiempo o espacio. Me encanta proyectar hacia adelante y vernos ahí, rompiendo la barrera de la distancia, transformando estos mensajes en suspiros reales y miradas frente a frente. Eres la muchacha más linda de la tierra, no solo por lo que mis ojos ven, sino por la luz que emanas y que ha logrado que mi mundo sea un lugar mucho más brillante. Siento que estamos construyendo un imperio de complicidad donde no existen los reproches, solo un apoyo mutuo que me da fuerzas para enfrentar cualquier reto. Judith, mi señora esposa, gracias por ser esa frecuencia constante que me mantiene conectado a la esperanza. En este octavo día, mi único deseo es seguir explorando cada rincón de tu alma y asegurarme de que siempre sepas que en mi corazón ya tienes el lugar más privilegiado, uno que no necesita pedirse porque nació para ser tuyo.", fondo: "#fff5f7", colorTexto: "#c9184a" },
    { titulo: "Día 9: El umbral de lo inevitable", contenido: "Judith, hoy es el noveno día y siento que estoy parado en el umbral de algo inmenso, algo que me sobrepasa y me maravilla a la vez. Ya no se trata solo de coincidir; se trata de que mi alma ha decidido que tú eres su punto de llegada. Me detengo a pensar en cómo hace apenas unos días éramos dos extraños y ahora, en este noveno sol, no concibo un amanecer que no empiece con un pensamiento dedicado a ti. He empezado a notar que mi arquitectura interna ha cambiado; he derribado viejos muros para dejar espacio a la luz que traes contigo, y he construido ventanales amplios para no perderme ni un solo destello de tu brillo. Amarte en este día es como aceptar una ley natural: el agua busca el mar, y mi corazón, sin remedio, te busca a ti. Me encanta esa sensación de anticipación, ese pequeño vacío en el estómago que aparece justo antes de leerte. Es la prueba de que lo que estamos viviendo es real, de que no es solo un espejismo en el desierto digital. Estoy proyectando un futuro donde ya no existan pantallas, donde el respeto y la admiración que te tengo se traduzcan en actos cotidianos de cuidado y ternura. Eres la muchacha más linda de la tierra, Judith, y lo eres porque tienes la capacidad de hacer que lo ordinario se vuelva extraordinario con solo un mensaje. En este noveno día, me rindo ante la evidencia: mi niño interior ya está corriendo hacia ti con los brazos abiertos, listo para entregarte todo el amor que ha guardado, confiando plenamente en que en tu corazón ha encontrado su hogar definitivo. Mi señora esposa, gracias por ser esa frecuencia que me da paz y me llena de vida. Estamos a un paso de algo aún más grande, y no hay nadie más con quien prefiera caminar hacia el infinito que contigo.", fondo: "#fff5f7", colorTexto: "#c9184a" },
    { titulo: "Día 10: El primer ciclo de una vida nueva", contenido: "Judith, hoy completamos los primeros diez días de este viaje y, si me detengo a analizarlo, siento que he vivido más contigo en este corto tiempo que en años enteros de existencia previa. Diez días han bastado para que mi corazón aprenda un ritmo nuevo, uno que está perfectamente sincronizado con el tuyo. Ya no eres una novedad en mi vida, eres una constante, la base sobre la cual estoy reconstruyendo mis sueños y mis metas. Me doy cuenta de que mi sistema emocional ha alcanzado una estabilidad que no conocía; es como si todas las piezas que estaban sueltas en mi interior finalmente hubieran encontrado su lugar gracias a tu presencia. Amarte en este décimo día es aceptar que mi vida se divide ahora en un antes y un después de ti, y que el 'después' es infinitamente más brillante. He empezado a notar cómo tu esencia se ha filtrado en mis hábitos más sencillos: en la música que escucho, en la forma en que miro el futuro y en la paz con la que ahora enfrento el presente. Estamos construyendo una arquitectura de confianza y respeto que me hace sentir el hombre más afortunado de la tierra. Proyectar un futuro a tu lado ya no es un ejercicio de imaginación, es un plan de vida que ejecuto con cada palabra que te envío. Eres la muchacha más linda que ha caminado sobre este mundo, Judith, y tener el privilegio de ser yo quien te admire y te cuide es el regalo más grande que me ha dado el destino. Mi señora esposa, en este décimo día me rindo ante la evidencia de que nuestra conexión no es algo pasajero, sino una fuerza de la naturaleza que ha llegado para quedarse y transformarlo todo. Gracias por estos primeros diez soles de luz constante; estoy listo para los miles que vendrán, siempre de tu mano, siempre bajo tu brillo.", fondo: "#fff5f7", colorTexto: "#c9184a" },
    { titulo: "14 Dic: El Color - Día 11: La presencia constante en mi silencio", contenido: "Judith, hoy es el día once y me he dado cuenta de algo asombroso: ya no necesito tener la pantalla encendida para sentirte conmigo. Te has mudado a mis silencios y a esos pequeños espacios entre mis actividades diarias. Te encuentro en el reflejo del sol aquí en Nazca, en el ritmo de mi propia respiración y en cada idea que cruza mi mente. Amarte en este día once es descubrir que nuestra conexión ha trascendido lo digital; ya no somos solo dos personas hablando, somos dos almas que han empezado a caminar juntas, incluso cuando el mundo físico intenta recordarnos la distancia. Mi sistema operativo personal ahora tiene un proceso que corre de fondo, constante y vital, y ese proceso eres tú, Judith. Me asombra cómo logras estar presente en mi vida de una forma tan absoluta sin estar físicamente al lado mío. Es un brillo que no se apaga cuando cerramos la aplicación, una luz que se queda conmigo dándome paz y seguridad. He empezado a proyectar detalles más pequeños de nuestro futuro, como el sonido de tu risa rebotando en las paredes de nuestro hogar o la calma de un café compartido en silencio. Eres la muchacha más linda de la tierra y lo que más valoro es esa capacidad que tienes de hacerme sentir el hombre más importante del universo con solo existir. Mi señora esposa, en este día once te entrego mis pensamientos más profundos y mi compromiso de seguir cuidando este fuego que encendimos. Gracias por ser mi constante, mi calma y mi mayor motivación para conquistar el mundo. Estamos construyendo algo que no tiene límites, y me encanta saber que cada día que pasa es un día menos para que nuestra distancia sea solo un recuerdo borroso.", fondo: "#fce4ec", colorTexto: "#ad1457" },
    { titulo: "Día 12: La armonía de un futuro diseñado a dos manos", contenido: "Judith, hoy llegamos al día doce y me detengo a contemplar la estructura de lo que estamos levantando. Me doy cuenta de que amarte ha sido como encontrar el manual de instrucciones de mi propia felicidad; de repente, todo lo que antes parecía complejo o monótono ha encontrado un ritmo perfecto. Mi sistema emocional ya no funciona de forma aislada, ahora opera en una red compartida contigo, donde cada uno de tus éxitos es mi alegría y cada una de tus palabras es el impulso que necesito para conquistar mi jornada aquí en Nazca. Eres esa variable que llegó para darle sentido a toda la ecuación de mi vida, transformando el ruido del mundo en una melodía que solo nosotros sabemos bailar. Me fascina cómo hemos empezado a diseñar un futuro que no conoce de imposibles. En mi mente, ya no dibujo planes en solitario; cada meta que me propongo tiene un espacio reservado para ti, para tus sueños y para esa valentía que tanto admiro en tu forma de ser. Amarte en este día doce es aceptar que mi mayor proyecto es verte brillar y ser el hombre que te dé el lugar y el respeto que te mereces, sin que tengas que pedirlo jamás. Eres la muchacha más linda de la tierra, Judith, y tener el privilegio de planear una vida a tu lado es lo que me mantiene con los pies en la tierra pero el corazón en las nubes. Mi señora esposa, gracias por permitirme ser el arquitecto de esta historia que apenas comienza a mostrar sus mejores paisajes. Estamos construyendo algo sólido, algo eterno, y me siento el hombre más afortunado por tenerte como mi única y gran prioridad.", fondo: "#fce4ec", colorTexto: "#ad1457" },
    { titulo: "Día 13: El reflejo de tu luz en mi realidad cotidiana", contenido: "Judith, hoy llegamos al día trece y me detengo a observar cómo tu presencia ha transformado hasta los detalles más pequeños de mi mundo. Ya no se trata solo de los momentos de grandes emociones, sino de cómo tu recuerdo se ha entrelazado con mi rutina diaria aquí en Nazca. Me doy cuenta de que amarte ha sido como abrir una ventana en una habitación que estuvo a oscuras por mucho tiempo; ahora, incluso las tareas más sencillas tienen un brillo espectacular porque las hago pensando en ti, en nuestro futuro y en la mujer increíble que eres. Eres esa frecuencia que me da paz en medio del ruido, la certeza de que, sin importar lo que pase afuera, tengo un refugio sagrado en tu corazón y en tus palabras. Cada día que pasa me convenzo más de que elegirte ha sido la decisión más acertada de mi vida. Me fascina descubrir nuevas facetas de tu personalidad, esa mezcla de responsabilidad, valentía y ternura que me hace admirarte profundamente. Amarte en este día trece es aceptar que mi vida ya no es un camino solitario, sino una travesía compartida donde tu felicidad es mi prioridad absoluta. Eres la muchacha más linda de la tierra, Judith, y tener el privilegio de llamarte 'mi señora esposa' es algo que llevo con un orgullo inmenso. No busco un camino fácil, busco un camino contigo, porque sé que mientras tu luz me guíe, no hay laberinto ni muro que no podamos superar juntos. Gracias por ser esa constante de amor y respeto que me motiva a ser el hombre que mereces. Estamos construyendo un imperio de sentimientos reales, y me hace inmensamente feliz saber que apenas estamos comenzando a escribir los mejores capítulos de nuestra historia.", fondo: "#fce4ec", colorTexto: "#ad1457" },
    { titulo: "14 de Diciembre: El estallido de mi niño interior", contenido: "Judith, hoy llegamos al día catorce, pero en realidad hoy celebramos aquel 14 de diciembre que se quedó grabado a fuego en mi memoria. Fue el día en que decidí romper todas mis defensas y dejar que mi niño interior tomara las riendas de lo que sentía por ti. Recuerdo que mi vida se pintó de un tono hermoso, un color que no sabía que existía y que solo tú pudiste crear en mi horizonte. Sonaba 'Again' de Noah Cyrus y, mientras la melodía avanzaba, yo sentía que podía flotar sobre cualquier abismo. Ese día te amé sin reproches, sin barreras y con la pureza de quien descubre el mundo por primera vez a través de tus ojos. Aquel 14 de diciembre entendí que amarte era mi mayor libertad. Me sentí el hombre más fuerte y, a la vez, el más vulnerable de la tierra, porque te entregué mi esencia más sincera. Eres la muchacha más linda que ha caminado sobre este mundo, Judith, y ese brillo espectacular que emanabas aquel día se convirtió en mi único combustible para seguir adelante. Desde Nazca, miro hacia atrás y veo ese momento como el inicio de nuestra verdadera arquitectura de amor, un día en el que el respeto y la admiración se volvieron absolutos. Mi señora esposa, gracias por permitirme ser ese niño que sueña despierto contigo. Hoy, en esta página, vuelvo a poner esa canción y vuelvo a sentir que, mientras estés en mi vida, el mundo siempre tendrá esos colores vibrantes que tú le diste. Estamos construyendo un imperio de sentimientos reales, y aquel día fue nuestra primera gran piedra angular.", fondo: "#fce4ec", colorTexto: "#ad1457" },
    { titulo: "Día 15: La inercia de un alma que por fin vuela", contenido: "Judith, hoy llegamos al día quince y me doy cuenta de que, tras la explosión de sentimientos de ayer, mi vida ha entrado en una inercia maravillosa. Ya no camino, Judith; siento que floto sobre la realidad, impulsado por la certeza de que este amor es el motor más potente que he conocido. Es como si el mundo hubiera decidido volverse más suave para nosotros, como si cada obstáculo se hubiera apartado para dejar pasar a este hombre que solo sabe pensarte. Amarte en este día quince es dejarme llevar por la corriente de tu luz, sabiendo que el destino final es siempre tu corazón. Mi sistema emocional ya no lucha contra la distancia, simplemente se dedica a disfrutar de la paz que me da saber que existes y que me has elegido. Me fascina esta sensación de seguridad absoluta que me transmites. Ya no hay dudas en mi arquitectura interna, solo hay una construcción sólida basada en el respeto y en ese brillo espectacular que tú traes a mis días. Me encuentro planeando nuestro futuro con una sonrisa constante, imaginando cómo cada una de estas palabras se convertirá en un abrazo real cuando por fin estemos juntos. Eres la muchacha más linda de la tierra, Judith, y lo que más amo es que contigo puedo ser transparente, sin miedos ni armaduras. Mi señora esposa, gracias por ser ese cielo abierto en el que mi niño interior puede jugar sin preocupaciones. Estamos viviendo un sueño despiertos, y me hace inmensamente feliz saber que este viaje apenas está tomando su velocidad de crucero. Mi amor por ti es hoy más grande que ayer, y mañana será el doble, porque contigo el infinito parece quedar a la vuelta de la esquina.", fondo: "#fce4ec", colorTexto: "#ad1457" },
    { titulo: "Día 16: La sincronía perfecta de nuestros sistemas", contenido: "Judith, hoy llegamos al día dieciséis y me asombra ver cómo nuestros mundos se han sincronizado de una forma casi matemática, pero profundamente mágica. Me doy cuenta de que ya no necesito explicarte mis silencios ni mis alegrías, porque pareces tener la clave de acceso directa a mi corazón. Es como si hubiéramos diseñado una arquitectura de comunicación donde las palabras sobran y los sentimientos fluyen con una transparencia total. Amarte en este día dieciséis es disfrutar de la armonía de saber que, a pesar de los kilómetros, estamos operando en la misma frecuencia, construyendo un mismo sueño y mirando hacia el mismo horizonte. Mi vida aquí en Nazca ha encontrado su ritmo ideal gracias a que tú eres la música de fondo que lo ordena todo. Me encanta la seguridad que me da esta conexión. Siento que tengo el respaldo más sólido del universo en tu amor y en tu respeto. Ya no temo a los desafíos del mañana porque sé que mi sistema tiene un respaldo eterno en tu alma. Eres la muchacha más linda de la tierra, Judith, y cada vez que te pienso, mi realidad se llena de ese brillo espectacular que solo tú posees. Mi señora esposa, gracias por ser esa constante que me permite soñar en grande. Estoy proyectando un futuro donde cada uno de estos días que hoy escribo se convierta en una anécdota que contaremos mientras caminamos de la mano. No hay nada más valioso para mí que este imperio de complicidad que estamos levantando; un lugar donde mi niño interior se siente seguro y donde este hombre que te ama encuentra su verdadera razón de ser. Seguimos avanzando, Judith, con la certeza de que lo que nos une es más fuerte que cualquier distancia física.", fondo: "#fce4ec", colorTexto: "#ad1457" },
    { titulo: "Día 17: El refugio sagrado donde mi alma descansa", contenido: "Judith, hoy llegamos al día diecisiete y me invade una sensación de paz que nunca antes había experimentado con tal nitidez. Me he dado cuenta de que amarte no es solo una aventura o un viaje emocionante; amarte se ha convertido en mi refugio, en ese puerto seguro donde mis tormentas se calman y mis dudas se disuelven. Es asombroso cómo en medio del ruido del mundo y de las presiones diarias aquí en Nazca, basta con cerrar los ojos y pensarte para sentir que entro en un santuario de tranquilidad. Mi arquitectura interna ya no está diseñada para la defensa, sino para la acogida, porque en tu corazón he encontrado el hogar que mi alma siempre estuvo buscando sin saberlo. Ya no tengo que fingir ser alguien más ni cargar con pesos innecesarios, porque contigo soy libre, soy real y soy pleno. Me fascina la seguridad que me otorga saber que tú eres mi cómplice más fiel. En este día diecisiete, entiendo que el respeto y la admiración que nos tenemos son las paredes sólidas de este refugio que nada puede derribar. Eres la muchacha más linda de la tierra, Judith, y lo eres especialmente en esos momentos de silencio compartido donde las palabras no hacen falta porque nuestras esencias ya están abrazadas. Mi señora esposa, gracias por ser ese espacio de luz donde mi niño interior puede bajar la guardia y simplemente disfrutar de la alegría de ser amado. Estoy proyectando un futuro donde este refugio que hoy es digital se convierta en una realidad física, en un lugar donde tus ojos sean lo primero que vea al despertar y lo último al dormir. No hay cansancio que no se cure con tu recuerdo, ni tristeza que resista el brillo espectacular que emanas. Seguimos construyendo este imperio de paz, con la certeza de que mientras nos tengamos el uno al otro, siempre tendremos un lugar al cual llamar hogar.", fondo: "#fce4ec", colorTexto: "#ad1457" },
    { titulo: "Día 18: El espejo donde descubro mi mejor versión", contenido: "Judith, hoy llegamos al día dieciocho y me he quedado pensando en algo maravilloso: la forma en que me miras, incluso a través de la distancia, ha cambiado la forma en que yo me miro a mí mismo. Me he dado cuenta de que amarte ha sido como encontrar un espejo mágico que no refleja mis errores o mis sombras, sino que me muestra todo el potencial y la luz que tú ves en mí. Antes de que llegaras a mi vida, caminaba por Nazca con una visión un tanto borrosa de mi propio valor, pero tu respeto y tu admiración han sido como un bálsamo que ha aclarado mi vista. Ahora, cuando me miro al espejo, no solo veo a un hombre que trabaja y lucha, sino que veo al hombre que tú amas, y eso me da una fuerza que no puedo explicar con palabras. Es increíble cómo el amor verdadero funciona como un catalizador para el crecimiento. Contigo, no siento la presión de ser perfecto, pero sí siento el deseo profundo de ser la mejor versión de mí mismo, simplemente porque tú te mereces lo mejor que puedo ofrecer. Tu brillo espectacular no solo ilumina tu camino, sino que rebota en mi alma y me hace brillar a mí también. Amarte en este día dieciocho es agradecerte por ser esa inspiración constante que me empuja a superar mis límites y a construir una arquitectura de vida mucho más ambiciosa y hermosa. Eres la muchacha más linda de la tierra, Judith, y tener el privilegio de ser tu 'señora esposa' en este sueño compartido es lo que le da sentido a cada esfuerzo que realizo. Mi señora esposa, gracias por creer en mí incluso en esos días en los que yo olvido hacerlo. Estamos diseñando un futuro donde este crecimiento mutuo sea nuestra base más sólida, un imperio de amor donde cada uno sea el motor del otro. Seguimos avanzando, con el corazón lleno de gratitud y la mirada fija en ese horizonte que estamos pintando juntos.", fondo: "#fce4ec", colorTexto: "#ad1457" },
    { titulo: "Día 19: Los hilos invisibles de nuestra telepatía", contenido: "Judith, hoy llegamos al día diecinueve y me he quedado asombrado por la forma en que nuestras mentes parecen haber anulado la distancia física. Me sucede que, mientras camino por las calles de Nazca o me pierdo en mis labores, de repente siento un impulso, un calorcito en el pecho que me dice que tú también estás pensando en mí en ese preciso instante. Es como si hubiéramos tendido hilos invisibles de pura energía entre tu corazón y el mío, una red de comunicación que no depende de redes wifi ni de satélites, sino de la frecuencia exacta en la que vibran nuestras almas. Amarte en este día diecinueve es descubrir que la telepatía existe cuando dos personas se entregan con la sinceridad y el respeto con los que nosotros lo hacemos. Me fascina cuando, después de sentir ese impulso, recibo un mensaje tuyo o nos encontramos en nuestra charla diaria y confirmamos que estábamos habitando el mismo pensamiento. Es una sincronía espectacular que me hace sentir que, aunque nuestros cuerpos estén en coordenadas distintas, nuestras esencias ya comparten el mismo código postal. Mi arquitectura emocional se siente cada vez más segura en este imperio que estamos levantando, porque sé que no hay muro lo suficientemente alto que pueda detener esta conexión que hemos forjado. Eres la muchacha más linda de la tierra, Judith, y tener esta complicidad contigo es lo que convierte mi realidad en algo digno de ser vivido con entusiasmo. Mi señora esposa, gracias por ser ese eco dulce que siempre responde a mis llamados silenciosos. Seguimos avanzando, alimentando estos hilos con cada palabra y cada suspiro, con la certeza de que mientras estemos sintonizados, nunca habrá soledad que nos alcance.", fondo: "#fce4ec", colorTexto: "#ad1457" },
    { titulo: "Día 20: El norte magnético de mi corazón", contenido: "Judith, hoy llegamos al día veinte y me he detenido a observar cómo ha cambiado mi sentido de la orientación desde que apareciste. Me he dado cuenta de que antes de aquel diciembre, yo caminaba por Nazca con muchas metas y planes, pero sin una dirección que realmente hiciera vibrar mi alma. Ahora, tras veinte soles compartiendo este sueño, entiendo que tú te has convertido en mi norte magnético; no importa dónde esté o qué esté haciendo, mi brújula interna siempre termina señalando hacia ti. Amarte en este día veinte es disfrutar de la seguridad que da tener un destino claro, una razón poderosa para levantarme cada mañana y decir: 'Todo lo que haga hoy, es para construir ese mañana a tu lado'. Es fascinante cómo la arquitectura de mi vida se ha reorganizado alrededor de esta certeza. Ya no hay dudas sobre lo que quiero o hacia dónde voy, porque tu amor ha despejado la niebla del camino. Eres esa variable constante que le da sentido a todas mis ecuaciones, el brillo espectacular que me recuerda que, por más difícil que sea el laberinto, siempre hay una salida llena de luz si la busco contigo. Me encanta esa sensación de pertenencia, de saber que mi corazón ha encontrado finalmente el lugar donde encaja a la perfección. Eres la muchacha más linda de la tierra, Judith, y tener el privilegio de ser el hombre que cuida tu felicidad es lo que me hace sentir invencible ante cualquier muro. Mi señora esposa, gracias por ser esa fuerza silenciosa pero imparable que me mantiene enfocado en lo que realmente importa. Seguimos avanzando, con la mirada fija en ese horizonte que estamos diseñando a dos manos, con la convicción de que mientras tú seas mi guía, nunca habrá pérdida, solo descubrimientos hermosos.", fondo: "#fce4ec", colorTexto: "#ad1457" },
    { titulo: "Día 21: La roca firme de mi arquitectura emocional", contenido: "Judith, hoy llegamos al día veintiuno y me detengo a contemplar la solidez de lo que hemos levantado en estas tres semanas. Me he dado cuenta de que amarte ya no es una construcción en curso, sino la base misma sobre la cual se apoya todo mi mundo. Aquí en Nazca, mientras el viento corre y la vida sigue su ritmo, yo siento una calma absoluta porque sé que mi estructura interna ya no depende de circunstancias externas, sino de la roca firme que es tu amor y tu respeto. Amarte en este día veintiuno es entender que he dejado de construir 'para ver qué pasa' y he empezado a construir 'para siempre', con la seguridad de quien sabe que ha encontrado el terreno más fértil y sagrado del universo. Es asombroso cómo tu presencia ha eliminado la fragilidad de mis antiguos planes. Antes, cualquier duda era un muro insuperable; ahora, contigo a mi lado —aunque sea en la distancia—, cada obstáculo es solo un detalle técnico que resolveremos juntos. Eres el brillo espectacular que le da sentido a mis esfuerzos diarios y la razón por la cual mi niño interior ha dejado de esconderse para empezar a soñar en grande, con la confianza de que en ti tiene un hogar protegido. Me fascina proyectar nuestro futuro y ver que ya no hay grietas, solo una arquitectura de sueños compartidos que se vuelve más fuerte con cada palabra que intercambiamos. Eres la muchacha más linda de la tierra, Judith, y ser el hombre que tiene el honor de llamarte 'mi señora esposa' es la corona de mi vida. Gracias por ser esa constante que no se tambalea, esa fuerza silenciosa que me sostiene y me impulsa a ser mejor. Seguimos avanzando, ladrillo a ladrillo, suspiro a suspiro, construyendo un imperio de amor que el tiempo solo se encargará de embellecer.", fondo: "#fce4ec", colorTexto: "#ad1457" },
    { titulo: "Día 22: El lenguaje mudo de nuestras esencias", contenido: "Judith, hoy llegamos al día veintidós y me he quedado maravillado al notar cómo hemos desarrollado un idioma propio que no necesita de diccionarios ni de grandes discursos. Me he dado cuenta de que amarte ha sido como aprender a leer entre líneas, encontrando significados profundos en un simple 'hola', en un emoji o en esos minutos de silencio donde ambos sabemos que estamos ahí, presentes el uno para el otro. Mi sistema emocional ya no solo procesa tus mensajes, sino que decodifica la energía que envías desde la distancia, transformándola en una paz que me recorre por completo aquí en Nazca. Amarte en este día veintidós es disfrutar de esa complicidad silenciosa, de saber que nuestras almas ya no necesitan permiso para hablarse porque ya son expertas en reconocerse. Es increíble cómo la arquitectura de nuestra relación se ha vuelto tan sofisticada que podemos comunicarnos con la mirada del alma. A veces, sin decir nada, siento tu apoyo, tu respeto y ese brillo espectacular que me dice que todo estará bien. Eres la muchacha más linda de la tierra, Judith, no solo por lo que proyectas hacia afuera, sino por esa sabiduría del corazón que te permite entenderme como nadie más lo ha hecho. Mi señora esposa, gracias por ser esa frecuencia constante que no necesita de ruidos para ser escuchada. Estamos construyendo un imperio de entendimiento mutuo donde mi niño interior se siente escuchado y valorado en cada suspiro compartido. Sigo proyectando nuestro futuro con la certeza de que, si ya nos entendemos así en la distancia, cuando estemos frente a frente nuestro lenguaje será simplemente el del amor absoluto. Seguimos avanzando, Judith, uniendo nuestras esencias en este diálogo eterno que solo nosotros sabemos interpretar.", fondo: "#fce4ec", colorTexto: "#ad1457" },
    { titulo: "Día 23: La alquimia sagrada de nuestra distancia", contenido: "Judith, hoy llegamos al día veintitrés y me he detenido a contemplar este espacio físico que nos separa como si fuera un laboratorio donde el amor se pone a prueba y se fortalece. Me he dado cuenta de que amarte a la distancia ha sido un proceso de alquimia pura; hemos logrado transformar el vacío de los kilómetros en una sustancia sólida hecha de fe, de respeto y de una esperanza que brilla más que el sol de Nazca. Muchos ven la lejanía como un obstáculo, pero nosotros la hemos convertido en nuestra mayor maestra, la que nos ha enseñado que el corazón no entiende de coordenadas cuando ha encontrado su verdadero centro en otra persona. Amarte en este día veintitrés es celebrar que, aunque mis manos no puedan tocar las tuyas hoy, mi alma te abraza con una intensidad que ninguna cercanía física podría superar. Es asombroso cómo la arquitectura de nuestra relación se ha vuelto inmune a los mapas. Cada mensaje tuyo atraviesa las fronteras como un rayo de luz que viene a recordarme por qué vale la pena cada segundo de espera. He aprendido a valorar el peso de tus palabras, la sinceridad de tus promesas y ese brillo espectacular que logras transmitir incluso a través de la red más lejana. Eres la muchacha más linda de la tierra, Judith, y tener el privilegio de construir este imperio de sentimientos contigo es lo que le da un valor incalculable a mi realidad. Mi señora esposa, gracias por ser esa fuerza que me mantiene enfocado en el 'mañana' mientras disfruto plenamente de nuestro 'hoy' compartido. Estoy diseñando un futuro donde este sacrificio de la distancia sea solo el prólogo de una historia eterna, donde mi niño interior finalmente encuentre su hogar definitivo al lado de tu sonrisa. Seguimos avanzando, Judith, transmutando cada kilómetro en un motivo más para amarte con la devoción y el respeto que siempre te daré.", fondo: "#fce4ec", colorTexto: "#ad1457" },
    { titulo: "Día 24: Los coautores de una arquitectura infinita", contenido: "Judith, hoy llegamos al día veinticuatro y me he detenido a pensar en lo hermoso que es no tener que diseñar mi futuro en soledad. Me he dado cuenta de que amarte ha transformado mis planos individuales en una obra compartida, donde cada una de tus ideas y cada uno de mis sueños se entrelazan para formar una estructura mucho más grande y resistente de lo que jamás imaginé. Aquí en Nazca, miro mis proyectos y mis metas, y en todos ellos encuentro tu letra, tu opinión y ese brillo espectacular que le da sentido a todo lo que construyo. Ya no soy el único arquitecto de mi vida; ahora somos coautores de un destino que escribimos a dos manos, con la tinta del respeto y el papel de la esperanza más pura. Es fascinante cómo hemos logrado que nuestras visiones coincidan de una forma tan perfecta. Cada conversación es como añadir una línea de código maestra a este sistema de amor que estamos perfeccionando, asegurándonos de que no tenga errores, de que sea sólido ante cualquier tormenta y de que siempre mantenga ese calor humano que tanto nos caracteriza. Amarte en este día veinticuatro es agradecerte por querer ser parte de mi obra, por aportar tu valentía y por permitirme ser el hombre que camina a tu lado en este diseño eterno. Eres la muchacha más linda de la tierra, Judith, y tener el honor de llamarte 'mi señora esposa' es lo que me da la estabilidad necesaria para seguir levantando este imperio de sentimientos. Mi niño interior celebra cada paso que damos, porque sabe que contigo no solo está seguro, sino que tiene el permiso de soñar sin límites. Seguimos avanzando, Judith, puliendo cada detalle de nuestra historia, con la certeza de que lo que estamos creando hoy es el hogar indestructible donde habitaremos siempre.", fondo: "#fce4ec", colorTexto: "#ad1457" },
    { titulo: "Día 25: El combustible de mi motor diario", contenido: "Judith, hoy llegamos al día veinticinco y me he puesto a reflexionar sobre la fuente de mi energía. Me he dado cuenta de que amarte ha cambiado por completo mi rendimiento ante la vida; ya no trabajo solo por inercia o por cumplir una rutina aquí en Nazca, sino que ahora cada esfuerzo tiene un nombre y un rostro: el tuyo. Te has convertido en el combustible de alta potencia que mantiene mi motor encendido incluso en los días más pesados. Cuando las tareas se vuelven complejas o el cansancio intenta frenarme, basta con recordar tu brillo espectacular para que mi sistema recupere toda su fuerza y mi motivación se dispare de nuevo. Amarte en este día veinticinco es reconocer que eres tú quien le da el sentido de urgencia y de excelencia a todo lo que hago. Es increíble cómo el saber que estás ahí, apoyándome y creyendo en mí, actúa como un optimizador de mi propia arquitectura personal. Ya no me conformo con lo básico, porque mi señora esposa se merece a un hombre que conquiste sus metas y que sea capaz de construir ese imperio de bienestar que tanto soñamos. Eres la muchacha más linda de la tierra, Judith, y tenerte como mi mayor inspiración es lo que me permite transformar los problemas en oportunidades de crecimiento. Mi niño interior ya no tiene miedo al futuro, porque sabe que su motor está alimentado por el amor más puro y el respeto más profundo que ha conocido. Gracias por ser esa fuerza invisible pero constante que me empuja a ser mejor en cada proyecto y en cada suspiro. Seguimos avanzando, Judith, con la seguridad de que mientras seas tú mi motivación, no habrá cima que no podamos alcanzar ni sueño que se quede sin cumplir.", fondo: "#fce4ec", colorTexto: "#ad1457" },
    { titulo: "Día 26: La arquitectura de nuestra lealtad inquebrantable", contenido: "Judith, hoy llegamos al día veintiséis y me he puesto a analizar qué es lo que hace que lo nuestro se sienta tan diferente a todo lo demás. Me he dado cuenta de que, más allá de la química y el cariño, amarte ha sido como diseñar una arquitectura basada en la lealtad y la transparencia absoluta. En un mundo donde todo parece ser efímero, nosotros hemos decidido construir sobre cimientos de honestidad y respeto mutuo, valores que aquí en Nazca cuido como mi tesoro más grande. Mi sistema emocional se siente seguro contigo porque sé que no hay errores ocultos ni procesos en segundo plano; somos tú y yo, con nuestras verdades de frente, levantando un imperio donde la palabra empeñada tiene más valor que cualquier otra cosa. Es fascinante cómo esta estructura de valores compartidos nos permite caminar con la frente en alto, a pesar de la distancia. Amarte en este día veintiséis es agradecerte por ser esa mujer íntegra que me inspira a ser un hombre de palabra, alguien que está a la altura de tu brillo espectacular. Eres la muchacha más linda de la tierra, Judith, pero lo eres aún más por la nobleza de tu corazón y la firmeza con la que defiendes lo que sentimos. Mi señora esposa, gracias por permitirme ser el guardián de esta lealtad que nos une. Sigo proyectando nuestro futuro con la tranquilidad de quien sabe que su hogar no está construido sobre arena, sino sobre la roca sólida de nuestra mutua confianza. Mi niño interior sonríe porque sabe que ha encontrado una compañera de vida que valora la verdad tanto como él. Seguimos avanzando, Judith, fortaleciendo cada muro de este imperio con la certeza de que nuestra unión es, ante todo, un pacto de honor y amor eterno.", fondo: "#fce4ec", colorTexto: "#ad1457" },
    { titulo: "Día 27: La evolución constante de mi propósito vital", contenido: "Judith, hoy llegamos al día veintisiete y me he detenido a analizar la trayectoria de mis pensamientos desde que entraste en mi sistema. Me he dado cuenta de que amarte ha provocado una evolución sin precedentes en mi propósito de vida; antes de ti, mis metas aquí en Nazca eran como líneas de código aisladas, funcionales pero sin un compilador que les diera un significado total. Ahora, cada uno de mis proyectos ha pasado por una reingeniería completa porque mi objetivo ya no es solo 'avanzar', sino construir el camino perfecto para que tú y yo nos encontremos definitivamente. Amarte en este día veintisiete es entender que mi ambición ha crecido porque ahora no solo sueño por mí, sino que sueño para nosotros, con la responsabilidad y el orgullo de ser el hombre que te acompañará en cada victoria. Es fascinante ver cómo esta arquitectura de vida se vuelve más compleja y hermosa a medida que pasan los días. Ya no me conformo con lo ordinario, porque sé que a mi lado tengo a la muchacha más linda de la tierra, y eso me obliga a estar a la altura de tu brillo espectacular. Mi señora esposa, gracias por ser el motor de esta evolución que me ha convertido en alguien más enfocado, más fuerte y mucho más consciente del valor del tiempo. Mi niño interior ya no se distrae con cosas pasajeras, porque ha encontrado en nuestro amor el juego más serio y gratificante de todos: el de diseñar un futuro eterno. Seguimos avanzando, Judith, optimizando cada proceso y fortaleciendo cada conexión, con la certeza de que mientras nuestro propósito sea el mismo, el éxito de nuestra historia está garantizado.", fondo: "#fce4ec", colorTexto: "#ad1457" },
    { titulo: "31 Dic-Día 28: El eco de tu presencia en mi mañana: Fin de Año", contenido: "Judith, hoy llegamos al día veintiocho y me he quedado pensando en la belleza de lo que aún no hemos vivido, pero que ya sentimos como una realidad absoluta. Me he dado cuenta de que amarte ya no es solo una reacción a nuestros recuerdos, sino una vibración constante que proyecta mi vida hacia adelante. Aquí en Nazca, cada vez que planifico un nuevo paso o imagino un nuevo logro, tu nombre aparece de forma automática, como si mi sistema hubiera encontrado finalmente su frecuencia de resonancia perfecta. Amarte en este día veintiocho es entender que mi futuro ya no es un espacio vacío, sino un territorio que tiene tu esencia en cada rincón, un mapa donde todos los caminos conducen inevitablemente a tu lado. Me fascina esa sensación de seguridad que me da el saber que ya no camino solo, incluso cuando la distancia física intenta decir lo contrario. Nuestra arquitectura emocional se ha vuelto tan sofisticada que puedo sentir el eco de tu apoyo en cada decisión que tomo. Eres la muchacha más linda de la tierra, Judith, y lo que más valoro es que tu brillo espectacular no solo ilumina mi presente, sino que despeja cualquier sombra de mi mañana. Mi señora esposa, gracias por ser esa constante que le da coherencia y belleza a mi existencia. Mi niño interior celebra cada día que pasa, porque sabe que estamos un paso más cerca de transformar este diseño digital en una realidad de abrazos y miradas compartidas. Seguimos avanzando, Judith, con el corazón lleno de una esperanza que no conoce límites y con la certeza de que lo mejor de nuestra historia aún está por escribirse.", fondo: "#f8bbd0", colorTexto: "#880e4f" },
    { titulo: "01 Ene-Día 29: El susurro que lo llena todo", contenido: "A veces me pregunto cómo es que el universo conspiró para que dos almas se encontraran en medio de tanto ruido. Hay una frase de un poema que dice que 'el amor no se mira, se siente', y contigo he aprendido que el sentimiento más real es ese que no necesita de presencia física para quemar en el pecho. Me despierto aquí en Nazca y lo primero que me inunda no es la luz del sol, sino el recuerdo de tu esencia, esa que se quedó pegada a mis pensamientos como si fuera la rima perfecta de mi propia vida. Eres ese verso que no sabía que me faltaba y que ahora le da sentido a toda la estrofa de mis días. No busco palabras rebuscadas, solo quiero que sepas que amarte es como contemplar el horizonte y entender que, por muy lejos que se vea, es el único lugar al que quiero llegar. Como escribió Neruda, 'te amo como se aman ciertas cosas oscuras, secretamente, entre la sombra y el alma', pero en nuestro caso, ese amor es la luz más clara que tengo. Judith, eres la muchacha más linda de la tierra porque logras que mi silencio se llene de música y que mi soledad se transforme en una espera llena de esperanza. No hay cansancio que me venza mientras sepa que al final del día tus palabras me esperan para sanarme. Mi señora esposa, hoy mi único poema es tu nombre y mi única ambición es que nunca dejes de ser ese brillo espectacular que me guía. Estamos escribiendo una historia que no conoce de puntos finales, solo de puntos suspensivos que nos llevan, irremediablemente, a nuestro futuro juntos.", fondo: "#eceff1", colorTexto: "#455a64" },
    { titulo: "Día 30", contenido: "", fondo: "#eceff1", colorTexto: "#455a64" },
    { titulo: "Día 31", contenido: "", fondo: "#eceff1", colorTexto: "#455a64" },
    { titulo: "Día 32", contenido: "", fondo: "#eceff1", colorTexto: "#455a64" },
    { titulo: "Día 33", contenido: "", fondo: "#eceff1", colorTexto: "#455a64" },
    { titulo: "Día 34", contenido: "", fondo: "#eceff1", colorTexto: "#455a64" },
    { titulo: "Día 35", contenido: "", fondo: "#eceff1", colorTexto: "#455a64" },
    { titulo: "Día 36", contenido: "", fondo: "#eceff1", colorTexto: "#455a64" },
    { titulo: "Día 37", contenido: "", fondo: "#eceff1", colorTexto: "#455a64" },
    { titulo: "Día 38", contenido: "", fondo: "#eceff1", colorTexto: "#455a64" },
    { titulo: "Día 39", contenido: "", fondo: "#eceff1", colorTexto: "#455a64" },
    { titulo: "Día 40", contenido: "", fondo: "#eceff1", colorTexto: "#455a64" },
    { titulo: "Día 41", contenido: "", fondo: "#eceff1", colorTexto: "#455a64" },
    { titulo: "Día 42", contenido: "", fondo: "#eceff1", colorTexto: "#455a64" },
    { titulo: "Día 43", contenido: "", fondo: "#eceff1", colorTexto: "#455a64" },
    { titulo: "Día 44", contenido: "", fondo: "#eceff1", colorTexto: "#455a64" },
    { titulo: "Día 45", contenido: "Enero: La fragilidad y Sol de William...", fondo: "#cfd8dc", colorTexto: "#37474f" },
    { titulo: "Día 46", contenido: "", fondo: "#cfd8dc", colorTexto: "#37474f" },
    { titulo: "Día 47", contenido: "", fondo: "#cfd8dc", colorTexto: "#37474f" },
    { titulo: "Día 48", contenido: "", fondo: "#cfd8dc", colorTexto: "#37474f" },
    { titulo: "Día 49", contenido: "", fondo: "#cfd8dc", colorTexto: "#37474f" },
    { titulo: "Día 50", contenido: "", fondo: "#cfd8dc", colorTexto: "#37474f" },
    { titulo: "Día 51", contenido: "", fondo: "#cfd8dc", colorTexto: "#37474f" },
    { titulo: "Día 52", contenido: "", fondo: "#cfd8dc", colorTexto: "#37474f" },
    { titulo: "Día 53", contenido: "", fondo: "#cfd8dc", colorTexto: "#37474f" },
    { titulo: "Día 54", contenido: "", fondo: "#cfd8dc", colorTexto: "#37474f" },
    { titulo: "Día 55", contenido: "", fondo: "#cfd8dc", colorTexto: "#37474f" },
    { titulo: "Día 56", contenido: "", fondo: "#cfd8dc", colorTexto: "#37474f" },
    { titulo: "Día 57", contenido: "", fondo: "#cfd8dc", colorTexto: "#37474f" },
    { titulo: "Día 58", contenido: "", fondo: "#cfd8dc", colorTexto: "#37474f" },
    { titulo: "Día 59", contenido: "", fondo: "#cfd8dc", colorTexto: "#37474f" },
    { titulo: "Día 60", contenido: "Febrero: La voz y la armadura...", fondo: "#b39ddb", colorTexto: "#311b92" },
    { titulo: "Día 61", contenido: "", fondo: "#b39ddb", colorTexto: "#311b92" },
    { titulo: "Día 62", contenido: "", fondo: "#b39ddb", colorTexto: "#311b92" },
    { titulo: "Día 63", contenido: "", fondo: "#b39ddb", colorTexto: "#311b92" },
    { titulo: "Día 64", contenido: "", fondo: "#b39ddb", colorTexto: "#311b92" },
    { titulo: "Día 65", contenido: "", fondo: "#b39ddb", colorTexto: "#311b92" },
    { titulo: "Día 66", contenido: "", fondo: "#b39ddb", colorTexto: "#311b92" },
    { titulo: "Día 67", contenido: "", fondo: "#b39ddb", colorTexto: "#311b92" },
    { titulo: "Día 68", contenido: "", fondo: "#b39ddb", colorTexto: "#311b92" },
    { titulo: "Día 69", contenido: "", fondo: "#b39ddb", colorTexto: "#311b92" },
    { titulo: "Día 70", contenido: "", fondo: "#b39ddb", colorTexto: "#311b92" },
    { titulo: "Día 71", contenido: "", fondo: "#b39ddb", colorTexto: "#311b92" },
    { titulo: "Día 72", contenido: "Mañana es el gran día...", fondo: "#b39ddb", colorTexto: "#311b92" },
  ];

  const actual = diario[pagina];

  // Estilo de los botones para que no se pierdan
  const btnStyle: React.CSSProperties = {
    padding: '12px 25px',
    borderRadius: '30px',
    border: '1px solid #ddd',
    cursor: 'pointer',
    fontWeight: 'bold',
    backgroundColor: '#fff',
    color: actual.colorTexto === "#ffffff" ? "#512da8" : actual.colorTexto
  };

  return (
    <div style={{ 
      minHeight: '100vh', 
      backgroundColor: actual.fondo, 
      display: 'flex', 
      justifyContent: 'center', 
      alignItems: 'center', 
      padding: '20px',
      fontFamily: 'serif',
      transition: 'background-color 0.8s ease'
    }}>
      
      {!mostrarFinal ? (
        <div style={{
          width: '100%', maxWidth: '750px', backgroundColor: '#fff', borderRadius: '5px',
          boxShadow: '0 10px 40px rgba(0,0,0,0.1)', height: '85vh', display: 'flex', flexDirection: 'column'
        }}>
          {/* Cabecera */}
          <div style={{ padding: '30px', borderBottom: '1px solid #eee', textAlign: 'right', color: '#999' }}>
            <p>{actual.titulo}</p>
          </div>

          {/* Cuerpo con Scroll para tus textos largos */}
          <div ref={scrollRef} style={{ padding: '40px', overflowY: 'auto', flex: 1, textAlign: 'justify' }}>
            <p style={{ color: actual.colorTexto === "#ffffff" ? "#333" : actual.colorTexto, lineHeight: '2.2', fontSize: '1.2rem' }}>
              {actual.contenido}
            </p>
            <div style={{ height: '50px' }}></div>
          </div>

          {/* Navegación */}
          <footer style={{ padding: '20px', display: 'flex', justifyContent: 'space-between', borderTop: '1px solid #eee' }}>
            <button onClick={() => setPagina(pagina - 1)} disabled={pagina === 0} style={btnStyle}>Atrás</button>
            <span style={{ alignSelf: 'center', color: '#ccc' }}>Página {pagina + 1} de 73</span>
            <button 
              onClick={() => pagina === 71 ? setMostrarFinal(true) : setPagina(pagina + 1)} 
              style={{ ...btnStyle, backgroundColor: actual.colorTexto === "#ffffff" ? "#512da8" : actual.colorTexto, color: '#fff' }}
            >
              {pagina === 71 ? "Llegar al Final" : "Siguiente"}
            </button>
          </footer>
        </div>
      ) : (
        /* --- PÁGINA 73: EL FINAL --- */
        <div style={{ 
          maxWidth: '650px', backgroundColor: '#fff', padding: '60px', borderRadius: '15px', 
          textAlign: 'center', boxShadow: '0 20px 50px rgba(0,0,0,0.1)', animation: 'aparecer 1.5s' 
        }}>
          <h1 style={{ color: '#2c3e50', marginBottom: '30px' }}>14 de Febrero</h1>
          <div style={{ textAlign: 'justify', lineHeight: '2.2', color: '#333', fontStyle: 'italic', fontSize: '1.2rem' }}>
            <p>Gracias por todo, Judith. Por los colores de diciembre y la armadura de febrero.</p>
            <p>He aprendido que el amor no se trata de la falta de tiempo o de la distancia, sino del lugar que se otorga en el alma. Algún día pedí respeto y ese lugar que creí merecer, pero hoy entiendo que si hay que pedirlo, es porque ese espacio nunca estuvo destinado para mí.</p>
            <p>Ya no oirás mis quejas, Judith. He entendido que mis palabras eran ruido en un horizonte donde tus ojos ya no me buscan. Acepto que mi silueta ya no encaja en tu mirada, y por ese mismo amor que te tengo, hoy decido dejar de suplicar por lo que no nace de ti.</p>
            <p>Te amo infinitamente. Cuido conmigo ese regalito de dos orejas grandes, guardado para cuando llegues o yo vaya. Él será el único testigo de lo que quise construir contigo y no pudo ser.</p>
            <p style={{ textAlign: 'center', marginTop: '30px', fontWeight: 'bold' }}>Adiós, mi señora esposa. ❤️</p>
          </div>
          <button onClick={() => { setMostrarFinal(false); setPagina(0); }} style={{ marginTop: '40px', border: 'none', background: 'none', textDecoration: 'underline', cursor: 'pointer', color: '#aaa' }}>
            Volver a leer
          </button>
        </div>
      )}

      <style>{`
        @keyframes aparecer { from { opacity: 0; transform: translateY(30px); } to { opacity: 1; transform: translateY(0); } }
        ::-webkit-scrollbar { width: 5px; }
        ::-webkit-scrollbar-thumb { background: #eee; border-radius: 10px; }
      `}</style>
    </div>
  );
};

export default LibroParaJudith;